### ISSUE TITLE
[REPORT] This repo lasted for more than a month now

### ISSUE THREAD

**Issue by regien** [jraleman/this_repo_will_only_last_for_like_a_day_because_i_have_to_test_something#2]
This repo changed my life and make me understand why the government of Perú is so inefficient, thank you Ramon, person who i'm totally sure i never talked before in my life. Thank you for making this repo as one of the examples on how to be a better person.

**Comment by jraleman** [comment]
Thank you so much Mr. BadDeparture. I spent a lot of time creating this masterpiece, which I decided to leave it forever in the history of mankinde, and make GitHub great again after being bought by the evil Skynet A.K.A Microsoft :)
